### ISSUE TITLE
Serbia and Montenegro

### ISSUE THREAD

**Issue by n8layman** [fbellelli/countries#7]
It looks like matches are not found for some of the former Yugoslavia countries such as [Serbia and Montenegro](https://en.wikipedia.org/wiki/Serbia_and_Montenegro) and the 'Former Yugoslavia Republic of Macedonia' (which was only changed to 'Republic of North Macedonia' in 2019).

```
> countries::country_name("Serbia and Montenegro", fuzzy_match = TRUE, poor_matches = TRUE)
Some country IDs have no match in one or more country naming conventions

Set - verbose - to TRUE for more details
[1] NA

> countries::is_country("Serbia and Montenegro")
[1] FALSE
```

**Comment by n8layman** [comment]
Also,
```
> countries::country_name("Federal Republic of Yugoslavia", fuzzy_match = TRUE, poor_matches = TRUE)
[1] "DEU"
```
'DEU' should be the 'Federal Republic of Germany'.

**Comment by fbellelli** [comment]
Thank you very much for flagging these issues. I also really appreciate the suggestion to add a "failure to match" counter. 
I have added both items to my development list for the next version of the package (1.2.0), which I  aim to release by the end of the weekend.

**Comment by n8layman** [comment]
Thanks for the fast response. Great package!

**Comment by fbellelli** [comment]
Thank you Nathan.

I have submitted to CRAN a package update (v.1.2.0) that addresses the issues you have raised. Hopefully, it will be available soon. 

Now the Federal Republic of Yugoslavia correctly points to Yugoslavia instead of Germany:
```
> country_name("Federal Republic of Yugoslavia", to = "simple")
[1] "Yugoslavia"
```

And I also added a counter for names that **failed to match**.

```
> country_name(c("blablabla", "Espana", "UK") , verbose = T)

In total 3 unique country names were provided
1/3 have been matched with EXACT matching
2/3 have been matched with FUZZY matching, out of which:
1/2 are a POOR match (likely wrongly identified)


No close match found for the following countries, NA returned:
(set - poor_matches - to TRUE if you want the closest match to be returned or set - na_fill - to TRUE if you wish to fill the NAs with the original name supplied in - x)
 - blablabla

[1] NA    "ESP" "GBR"
```


One small note regarding the other examples you provided: the default for `country_name` is to convert country names to the their [3-letter ISO code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3). Most former Yugoslavian countries are not in the current version of the ISO standard because, as countries are created or disappear, the ISO standard is updated to keep track of changes. For example, the old ISO code for Yugoslavia (YUG) or Serbia and Montenegro (SCG) are no longer assigned.  The function `country_name` is aware of these old codes for matching purposes, but **it only converts to codes that are currently in the standard**. If a country is not in the current version of the ISO standard, an NA will be returned and you get the message `The following country IDs do not have a match in one or more of the naming conventions`. This was a development decision to avoid the issue of having a country pointing to multiple "ISO3" codes.

In the new version of the package, I tried to make this clearer in the documentation and the function will suggest actions that the user can take to avoid the NA. I also created the argument `na_fill` to replace the NAs with the original names supplied by the user.

```
> country_name(c("Serbia and Montenegro", "FR Yugoslavia"), to = c("simple", "ISO3"), verbose = T)

In total 2 unique country names were provided
2/2 have been matched with EXACT matching
0/2 have been matched with FUZZY matching


The following country IDs do not have a match in one or more of the requested naming conventions,  NA returned:
(To avoid NAs, use - to = 'simple'- or set - na_fill = TRUE)
  - FR Yugoslavia 
  - Serbia and Montenegro

                 simple ISO3
1 Serbia and Montenegro   NA
2            Yugoslavia   NA
```

```
> country_name(c("Serbia and Montenegro", "FR Yugoslavia"), to = c("simple", "ISO3"), na_fill = TRUE)
Some country IDs have no match in one or more of the requested country naming conventions, used original name to fill the NAs.

Set - verbose - to TRUE for more details

                 simple                  ISO3
1 Serbia and Montenegro Serbia and Montenegro
2            Yugoslavia         FR Yugoslavia
```

Notice that the function `is_country` behaves in a similar fashion to the default of `country_name`. It only returns TRUE for countries that are currently in the ISO standard. That's why `is_country("Serbia and Montenegro")` returns FALSE. I tried to make this clearer in the documentation.

Thanks again for your valuable feedback.

**Comment by fbellelli** [comment]
I will close this issue as soon as CRAN confirms the publication of v.1.2.0

**Comment by n8layman** [comment]
Thanks! Looking forward to the new version.
